---
title: "Compound Data Structure Drills"
type: "challenge"
visibility: "onsite"
description: "Compound Data Structure Drills"
depends: "rock-paper-scissors"
ignore:
- "compound-data-structure-drills.md"
